Enable elasticsearch headers and exclude unused plugins
omc/telegraf pull request #4
Opened 2021-12-14 11:46 UTC by samoen

### What are we Doing?

We are shrinking the binary size of shipit-telegraf builds by excluding plugins we do not use.

The omc branch has been rebased onto the latest release of telegraf - v1.20.4. Therefore I have squashed our elasticsearch headers patch into this commit. 

Some changes to the README were also required to pass the lint check in GitHub Actions that telegraf v1.20.4 itself did not pass (See commit in tree [https://github.com/influxdata/telegraf/tree/v1.20.4](https://github.com/influxdata/telegraf/tree/v1.20.4))

I also added a GitHub Action to ensure changes we make to the repo still successfully builds a binary. A go test step could also be added - however currently many tests assume all plugins are imported so it would require putting testing.T.skip() in most of the plugin tests.

Closes [omc/shipit-telegraf#27](https://github.com/omc/shipit-telegraf/issues/27)

2021-12-14 16:18 UTC, drusellers approved these changes

2021-12-14 16:21 UTC, dansimpson requested changes
There are some missing input plugins we depend on. See comment in other issue.

2021-12-15 03:17 UTC, samoen commented
> There are some missing input plugins we depend on. See comment in other issue.

Oh woops I was not familiar with the telegraf config, thanks.

2022-01-25 01:57 UTC, dansimpson approved these changes

2022-02-01 08:54 UTC, merged